version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: enzyme-adapter-react-16
    versions:
    - 1.15.6
  - dependency-name: react-tooltip
    versions:
    - 4.2.15
  - dependency-name: html-webpack-plugin
    versions:
    - 4.5.1
    - 5.2.0
  - dependency-name: react-select
    versions:
    - 4.0.2
    - 4.1.0
  - dependency-name: react-app-rewired
    versions:
    - 2.1.8
  - dependency-name: marked
    versions:
    - 1.2.8
  - dependency-name: react-scripts
    versions:
    - 4.0.1
